repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: bedag
    url: https://bedag.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 4.12.3
    values:
      - values/ingress-nginx.yaml
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager/cert-manager
    disableValidationOnInstall: true
    version: 1.18.1
    values:
      - values/cert-manager.yaml
  - name: cert-manager-config
    namespace: cert-manager
    chart: bedag/raw
    version: 2.0.0
    values:
      - values/cert-manager-config.yaml
    needs:
      - cert-manager
  - name: external-dns
    namespace: external-dns
    createNamespace: true
    chart: bitnami/external-dns
    disableValidationOnInstall: true
    version: 8.8.6
    values:
      - values/external-dns.yaml
  - name: letsencrypt
    namespace: cert-manager
    chart: bedag/raw
    version: 2.0.0
    values:
      - values/letsencrypt.yaml
  - name: loki
    namespace: loki
    createNamespace: true
    chart: grafana/loki
    version: 6.30.1
    values:
      - values/loki.yaml
  - name: alloy
    namespace: alloy
    createNamespace: true
    chart: grafana/alloy
    version: 1.1.2
    values:
      - values/alloy.yaml
  - name: grafana
    namespace: grafana
    createNamespace: true
    chart: grafana/grafana
    version: 9.2.10
    values:
      - values/grafana.yaml
    secrets:
      - secrets/grafana.secrets.yaml
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    wait: true
    chart: bitnami/postgresql
    version: 16.7.14
    values:
      - values/postgres.yaml
    secrets:
      - secrets/postgres.secrets.yaml
  - name: sample-django
    namespace: app
    createNamespace: true
    chart: ./charts/sample-django
    values:
      - values/sample-django.yaml
    secrets:
      - secrets/sample-django.secrets.yaml
