services: 
  db:
    image: postgres  
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass123
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U app -d django'"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"

  db-migration:
    build:
      context: ../
      dockerfile: ./djangodockertest/Dockerfile
    command: "python manage.py migrate"
    depends_on: 
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRESQL_DJANGO_USER}:${POSTGRESQL_DJANGO_PASSWORD}@db:${POSTGRESQL_PORT}/${POSTGRESQL_DJANGO_DATABASE}

  web:
    build:
      context: ../
      dockerfile: ./djangodockertest/Dockerfile
    command: "gunicorn mysite.wsgi:application --bind 0.0.0.0:80"
    ports:
      - "8888:80"
    depends_on: 
      db:
        condition: service_healthy
      db-migration:
        condition: service_started
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://${POSTGRESQL_DJANGO_USER}:${POSTGRESQL_DJANGO_PASSWORD}@db:${POSTGRESQL_PORT}/${POSTGRESQL_DJANGO_DATABASE}