---
- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx={{ nginx_version }}*
    state: latest
    update_cache: true

- name: Add configuration for the application
  become: true
  ansible.builtin.template:
    src: nginx_conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_conf_name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Run Nginx

- name: Remove the default configuration
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Run Nginx

- name: Enable the new configuration
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_conf_name }}"
    path: "/etc/nginx/sites-enabled/{{ nginx_conf_name }}"
    state: link
  notify:
    - Run Nginx