---
- name: Create the environment directory
  become: true
  ansible.builtin.file:
    path: "{{ app_env_dir_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create the environment file
  become: true
  ansible.builtin.template:
    src: django_env.j2
    dest: "{{ app_env_dir_path }}/environment"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: Restart gunicorn service

- name: Create a socket directory
  become: true
  ansible.builtin.file:
    path: /run/gunicorn
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
  notify: Start gunicorn socket

- name: Configure gunicorn.socket
  become: true
  ansible.builtin.template:
    src: gunicorn.socket.j2
    dest: /etc/systemd/system/gunicorn.socket
    mode: "0644"
  notify: Start gunicorn socket

- name: Configure gunicorn.service
  become: true
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    mode: "0644"
  notify: Start gunicorn socket
