---
- name: Install dependencies for Ansible
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest
  loop:
    - bash
    # - openssl
    # - libssl-dev
    # - libssl-doc
    # - acl

- name: Install dependencies for application
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - git
    - python3-dev
    - python3-venv
    - libpq-dev
    - gcc
