---
- name: Download 
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Download neccessary software 
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest
      loop:
        - git
        - python3-dev
        - libpq-dev
        - gcc
