apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-django.fullname" . }}
  labels:
    {{- include "sample-django.labels" . | nindent 4 }}
data:
  DJANGO_ALLOWED_HOSTS: {{ .Values.configmap.djangoAllowedHosts | quote }}
  {{- range .Values.configmap.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
