{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-django.fullname" . }}-postgres
  labels:
    {{- include "sample-django.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port | default 5432 }}/{{ .Values.postgres.database }}"
{{- end }}
