resources:
  - apiVersion: v1
    automountServiceAccountToken: true
    kind: ServiceAccount
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::290075658906:role/cert-manager-acme-dns01-route53
      name: cert-manager-acme-dns01-route53
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: cert-manager-acme-dns01-route53-tokenrequest
    rules:
      - apiGroups: [""]
        resources: ["serviceaccounts/token"]
        resourceNames: ["cert-manager-acme-dns01-route53"]
        verbs: ["create"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: cert-manager-acme-dns01-route53-tokenrequest
      namespace: cert-manager
    subjects:
      - kind: ServiceAccount
        name: cert-manager
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: cert-manager-acme-dns01-route53-tokenrequest
