---
- name: Install dependencies
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest
  loop:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - acl

- name: Install PostgreSQL
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - postgresql={{ postgresql_version }}*
    - postgresql-contrib={{ postgresql_version }}*
    - libpq-dev={{ postgresql_version }}*
    - python3-psycopg2
    
- name: Verify if the PostgreSQL service is running
  become: true
  service:
    name: postgresql
    state: started
    enabled: true